services:
  backend:
    build:
      context: ./server
    container_name: crm_node_backend
    env_file:
      - ./server/.env
    environment:
      - PORT=9010
    ports:
      - 9010:9010
    restart: unless-stopped
  frontend:
    build:
      context: ./client
    container_name: crm_node_frontend
    depends_on:
      - backend
    ports:
      - 9011:80
    restart: unless-stopped
